apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-consumer
  name: location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-consumer
  template:
    metadata:
      labels:
        service: location-consumer
    spec:
      initContainers:
        - name: kafka-check
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup kafka && nc -z 9092; do echo waiting for kafka service; sleep 5; done"]
      containers:
        - image: petetran/udaconnect-location-consumer:latest
          name: location-consumer
          imagePullPolicy: Always
          env:
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: KAFKA_URL
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: KAFKA_TOPIC
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name : DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
      restartPolicy: Always