# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n\x16LocationMessageRequest\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x31\n\rcreation_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x11\n\tlongitude\x18\x04 \x01(\t\"$\n\x16RetrieveMessageRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"c\n\x17LocationMessageResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tperson_id\x18\x02 \x01(\x05\x12\x12\n\ncoordinate\x18\x03 \x01(\t\x12\x15\n\rcreation_time\x18\x04 \x01(\t\"\x07\n\x05\x45mpty\"B\n\x13LocationMessageList\x12+\n\tlocations\x18\x01 \x03(\x0b\x32\x18.LocationMessageResponse2\x84\x01\n\x0fLocationService\x12;\n\x06\x43reate\x12\x17.LocationMessageRequest\x1a\x18.LocationMessageResponse\x12\x34\n\x03Get\x12\x17.RetrieveMessageRequest\x1a\x14.LocationMessageListb\x06proto3')



_LOCATIONMESSAGEREQUEST = DESCRIPTOR.message_types_by_name['LocationMessageRequest']
_RETRIEVEMESSAGEREQUEST = DESCRIPTOR.message_types_by_name['RetrieveMessageRequest']
_LOCATIONMESSAGERESPONSE = DESCRIPTOR.message_types_by_name['LocationMessageResponse']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_LOCATIONMESSAGELIST = DESCRIPTOR.message_types_by_name['LocationMessageList']
LocationMessageRequest = _reflection.GeneratedProtocolMessageType('LocationMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONMESSAGEREQUEST,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:LocationMessageRequest)
  })
_sym_db.RegisterMessage(LocationMessageRequest)

RetrieveMessageRequest = _reflection.GeneratedProtocolMessageType('RetrieveMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _RETRIEVEMESSAGEREQUEST,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:RetrieveMessageRequest)
  })
_sym_db.RegisterMessage(RetrieveMessageRequest)

LocationMessageResponse = _reflection.GeneratedProtocolMessageType('LocationMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONMESSAGERESPONSE,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:LocationMessageResponse)
  })
_sym_db.RegisterMessage(LocationMessageResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

LocationMessageList = _reflection.GeneratedProtocolMessageType('LocationMessageList', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONMESSAGELIST,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:LocationMessageList)
  })
_sym_db.RegisterMessage(LocationMessageList)

_LOCATIONSERVICE = DESCRIPTOR.services_by_name['LocationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONMESSAGEREQUEST._serialized_start=52
  _LOCATIONMESSAGEREQUEST._serialized_end=183
  _RETRIEVEMESSAGEREQUEST._serialized_start=185
  _RETRIEVEMESSAGEREQUEST._serialized_end=221
  _LOCATIONMESSAGERESPONSE._serialized_start=223
  _LOCATIONMESSAGERESPONSE._serialized_end=322
  _EMPTY._serialized_start=324
  _EMPTY._serialized_end=331
  _LOCATIONMESSAGELIST._serialized_start=333
  _LOCATIONMESSAGELIST._serialized_end=399
  _LOCATIONSERVICE._serialized_start=402
  _LOCATIONSERVICE._serialized_end=534
# @@protoc_insertion_point(module_scope)
